### ISSUE TITLE
Litentry Token Economy 

### ISSUE THREAD

**Issue by qiuhaiguo** [litentry/litentry-pallets#103]
The planning of Litentry token economy description and design:

- [ ] LIT token economy description
- [ ] LIT token utility cases research and description
- [ ] Governance research and design
- [ ] Token inflation model research and design
